In [3]:
# imports
import panel as pn
pn.extension('plotly')
import plotly.express as px
import pandas as pd
import hvplot.pandas
import matplotlib.pyplot as plt
import os
import numpy as np
from pathlib import Path
from dotenv import load_dotenv
import quandl

In [5]:
quandl.ApiConfig.api_key = '1wmkfWa67oX5XtNpGYsX'

In [10]:
state_home_prices = quandl.get("FMAC/HPI")
state_home_prices

,AK,AL,AR,AZ,CA,CO,CT,DC,DE,FL,...,TX,UT,VA,VT,WA,WI,WV,WY,United States not seasonaly adjusted,United States seasonaly adjusted
Date,,,,,,,,,,,,,,,,,,,,,
1975-01-31,34.371830,35.695975,36.738861,28.937735,15.722312,19.603977,24.369431,18.255987,27.264842,30.997043,...,32.602350,24.698474,27.912640,26.637620,17.484315,28.096764,41.002072,31.668794,23.497479,23.471007
1975-02-28,34.880945,35.896770,37.098962,29.463708,15.775202,19.837138,24.908036,18.382701,27.250734,32.229049,...,32.944116,25.060977,28.205810,26.956271,17.571053,28.486170,42.040473,32.161920,23.648785,23.629873
1975-03-31,35.402217,36.133518,37.416398,29.959514,15.964942,20.073483,25.313556,18.514587,27.268478,34.027506,...,33.542975,25.381341,28.420407,27.264731,17.689717,28.860737,43.122486,32.680525,23.895294,23.844527
1975-04-30,35.944703,36.425723,37.677813,30.345148,16.275547,20.301864,25.541141,18.689302,27.362673,36.218077,...,34.402826,25.627200,28.578762,27.546568,17.818792,29.185048,44.239196,33.210124,24.216495,24.111771
1975-05-31,36.535272,36.695708,37.921099,30.546449,16.533017,20.495075,25.614056,18.937116,27.561893,36.437855,...,34.649755,25.782334,28.717611,27.794738,17.933277,29.443523,45.363222,33.714128,24.416894,24.261528
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2017-08-31,180.767705,136.832464,143.883305,184.653324,221.827303,188.890036,138.899318,344.007270,161.484105,203.032387,...,190.405956,185.766048,188.244928,175.997419,217.172701,141.929765,147.276040,192.013542,178.982525,176.095178
2017-09-30,180.863076,137.182469,143.810889,185.082101,222.747758,189.247183,138.345405,342.079384,161.214510,204.479775,...,190.747517,186.219039,187.473673,175.630815,217.666449,141.704092,147.000202,192.303711,179.195171,177.150321
2017-10-31,180.642452,137.690921,143.815618,185.386919,223.013716,189.973594,137.688445,341.131417,160.357290,204.961848,...,191.001095,186.565591,186.848096,175.438235,218.375552,141.524015,146.961577,192.746245,179.214015,178.174761
2017-11-30,180.191092,137.905915,143.715639,185.808730,223.476329,190.468198,137.029819,341.367593,159.215701,205.148540,...,191.157777,186.978663,186.309152,175.451073,219.358413,141.158985,147.220056,193.252544,179.252146,179.252467
2017-12-31,180.140002,138.465286,143.535720,185.932453,224.416791,191.251430,136.368886,342.175252,158.169789,205.362563,...,191.614575,187.437632,185.522033,175.676196,220.553276,140.521333,147.220398,193.557479,179.339626,180.312876

In [12]:
IL_home_prices = state_home_prices["IL"]
IL_home_prices

Date
1975-01-31     25.670410
1975-02-28     25.766823
1975-03-31     25.969181
1975-04-30     26.232112
1975-05-31     26.396115
                 ...
2017-08-31    132.737242
2017-09-30    131.923579
2017-10-31    131.426941
2017-11-30    130.845756
2017-12-31    129.971841
Name: IL, Length: 516, dtype: float64